package test.model;

public class Doctorinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.id
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.uname
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.name
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.sex
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.title
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.edu
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private String edu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.hospitalName
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private String hospitalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctorinfo.hospitalUrl
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    private String hospitalurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.id
     *
     * @return the value of doctorinfo.id
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.id
     *
     * @param id the value for doctorinfo.id
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.uname
     *
     * @return the value of doctorinfo.uname
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.uname
     *
     * @param uname the value for doctorinfo.uname
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.name
     *
     * @return the value of doctorinfo.name
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.name
     *
     * @param name the value for doctorinfo.name
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.sex
     *
     * @return the value of doctorinfo.sex
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.sex
     *
     * @param sex the value for doctorinfo.sex
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.title
     *
     * @return the value of doctorinfo.title
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.title
     *
     * @param title the value for doctorinfo.title
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.edu
     *
     * @return the value of doctorinfo.edu
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public String getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.edu
     *
     * @param edu the value for doctorinfo.edu
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setEdu(String edu) {
        this.edu = edu == null ? null : edu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.hospitalName
     *
     * @return the value of doctorinfo.hospitalName
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public String getHospitalname() {
        return hospitalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.hospitalName
     *
     * @param hospitalname the value for doctorinfo.hospitalName
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setHospitalname(String hospitalname) {
        this.hospitalname = hospitalname == null ? null : hospitalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctorinfo.hospitalUrl
     *
     * @return the value of doctorinfo.hospitalUrl
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public String getHospitalurl() {
        return hospitalurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctorinfo.hospitalUrl
     *
     * @param hospitalurl the value for doctorinfo.hospitalUrl
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    public void setHospitalurl(String hospitalurl) {
        this.hospitalurl = hospitalurl == null ? null : hospitalurl.trim();
    }
}