package test.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DoctordataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public DoctordataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andActioncodeIsNull() {
            addCriterion("actioncode is null");
            return (Criteria) this;
        }

        public Criteria andActioncodeIsNotNull() {
            addCriterion("actioncode is not null");
            return (Criteria) this;
        }

        public Criteria andActioncodeEqualTo(String value) {
            addCriterion("actioncode =", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotEqualTo(String value) {
            addCriterion("actioncode <>", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeGreaterThan(String value) {
            addCriterion("actioncode >", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeGreaterThanOrEqualTo(String value) {
            addCriterion("actioncode >=", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeLessThan(String value) {
            addCriterion("actioncode <", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeLessThanOrEqualTo(String value) {
            addCriterion("actioncode <=", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeLike(String value) {
            addCriterion("actioncode like", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotLike(String value) {
            addCriterion("actioncode not like", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeIn(List<String> values) {
            addCriterion("actioncode in", values, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotIn(List<String> values) {
            addCriterion("actioncode not in", values, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeBetween(String value1, String value2) {
            addCriterion("actioncode between", value1, value2, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotBetween(String value1, String value2) {
            addCriterion("actioncode not between", value1, value2, "actioncode");
            return (Criteria) this;
        }

        public Criteria andTotalviewIsNull() {
            addCriterion("totalview is null");
            return (Criteria) this;
        }

        public Criteria andTotalviewIsNotNull() {
            addCriterion("totalview is not null");
            return (Criteria) this;
        }

        public Criteria andTotalviewEqualTo(String value) {
            addCriterion("totalview =", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewNotEqualTo(String value) {
            addCriterion("totalview <>", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewGreaterThan(String value) {
            addCriterion("totalview >", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewGreaterThanOrEqualTo(String value) {
            addCriterion("totalview >=", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewLessThan(String value) {
            addCriterion("totalview <", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewLessThanOrEqualTo(String value) {
            addCriterion("totalview <=", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewLike(String value) {
            addCriterion("totalview like", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewNotLike(String value) {
            addCriterion("totalview not like", value, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewIn(List<String> values) {
            addCriterion("totalview in", values, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewNotIn(List<String> values) {
            addCriterion("totalview not in", values, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewBetween(String value1, String value2) {
            addCriterion("totalview between", value1, value2, "totalview");
            return (Criteria) this;
        }

        public Criteria andTotalviewNotBetween(String value1, String value2) {
            addCriterion("totalview not between", value1, value2, "totalview");
            return (Criteria) this;
        }

        public Criteria andThanksIsNull() {
            addCriterion("thanks is null");
            return (Criteria) this;
        }

        public Criteria andThanksIsNotNull() {
            addCriterion("thanks is not null");
            return (Criteria) this;
        }

        public Criteria andThanksEqualTo(String value) {
            addCriterion("thanks =", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksNotEqualTo(String value) {
            addCriterion("thanks <>", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksGreaterThan(String value) {
            addCriterion("thanks >", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksGreaterThanOrEqualTo(String value) {
            addCriterion("thanks >=", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksLessThan(String value) {
            addCriterion("thanks <", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksLessThanOrEqualTo(String value) {
            addCriterion("thanks <=", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksLike(String value) {
            addCriterion("thanks like", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksNotLike(String value) {
            addCriterion("thanks not like", value, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksIn(List<String> values) {
            addCriterion("thanks in", values, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksNotIn(List<String> values) {
            addCriterion("thanks not in", values, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksBetween(String value1, String value2) {
            addCriterion("thanks between", value1, value2, "thanks");
            return (Criteria) this;
        }

        public Criteria andThanksNotBetween(String value1, String value2) {
            addCriterion("thanks not between", value1, value2, "thanks");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsIsNull() {
            addCriterion("warminggifts is null");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsIsNotNull() {
            addCriterion("warminggifts is not null");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsEqualTo(String value) {
            addCriterion("warminggifts =", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsNotEqualTo(String value) {
            addCriterion("warminggifts <>", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsGreaterThan(String value) {
            addCriterion("warminggifts >", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsGreaterThanOrEqualTo(String value) {
            addCriterion("warminggifts >=", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsLessThan(String value) {
            addCriterion("warminggifts <", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsLessThanOrEqualTo(String value) {
            addCriterion("warminggifts <=", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsLike(String value) {
            addCriterion("warminggifts like", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsNotLike(String value) {
            addCriterion("warminggifts not like", value, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsIn(List<String> values) {
            addCriterion("warminggifts in", values, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsNotIn(List<String> values) {
            addCriterion("warminggifts not in", values, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsBetween(String value1, String value2) {
            addCriterion("warminggifts between", value1, value2, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andWarminggiftsNotBetween(String value1, String value2) {
            addCriterion("warminggifts not between", value1, value2, "warminggifts");
            return (Criteria) this;
        }

        public Criteria andVotecountIsNull() {
            addCriterion("votecount is null");
            return (Criteria) this;
        }

        public Criteria andVotecountIsNotNull() {
            addCriterion("votecount is not null");
            return (Criteria) this;
        }

        public Criteria andVotecountEqualTo(String value) {
            addCriterion("votecount =", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountNotEqualTo(String value) {
            addCriterion("votecount <>", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountGreaterThan(String value) {
            addCriterion("votecount >", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountGreaterThanOrEqualTo(String value) {
            addCriterion("votecount >=", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountLessThan(String value) {
            addCriterion("votecount <", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountLessThanOrEqualTo(String value) {
            addCriterion("votecount <=", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountLike(String value) {
            addCriterion("votecount like", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountNotLike(String value) {
            addCriterion("votecount not like", value, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountIn(List<String> values) {
            addCriterion("votecount in", values, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountNotIn(List<String> values) {
            addCriterion("votecount not in", values, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountBetween(String value1, String value2) {
            addCriterion("votecount between", value1, value2, "votecount");
            return (Criteria) this;
        }

        public Criteria andVotecountNotBetween(String value1, String value2) {
            addCriterion("votecount not between", value1, value2, "votecount");
            return (Criteria) this;
        }

        public Criteria andTotalarticleIsNull() {
            addCriterion("totalarticle is null");
            return (Criteria) this;
        }

        public Criteria andTotalarticleIsNotNull() {
            addCriterion("totalarticle is not null");
            return (Criteria) this;
        }

        public Criteria andTotalarticleEqualTo(String value) {
            addCriterion("totalarticle =", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleNotEqualTo(String value) {
            addCriterion("totalarticle <>", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleGreaterThan(String value) {
            addCriterion("totalarticle >", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleGreaterThanOrEqualTo(String value) {
            addCriterion("totalarticle >=", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleLessThan(String value) {
            addCriterion("totalarticle <", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleLessThanOrEqualTo(String value) {
            addCriterion("totalarticle <=", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleLike(String value) {
            addCriterion("totalarticle like", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleNotLike(String value) {
            addCriterion("totalarticle not like", value, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleIn(List<String> values) {
            addCriterion("totalarticle in", values, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleNotIn(List<String> values) {
            addCriterion("totalarticle not in", values, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleBetween(String value1, String value2) {
            addCriterion("totalarticle between", value1, value2, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andTotalarticleNotBetween(String value1, String value2) {
            addCriterion("totalarticle not between", value1, value2, "totalarticle");
            return (Criteria) this;
        }

        public Criteria andLovingheartIsNull() {
            addCriterion("lovingheart is null");
            return (Criteria) this;
        }

        public Criteria andLovingheartIsNotNull() {
            addCriterion("lovingheart is not null");
            return (Criteria) this;
        }

        public Criteria andLovingheartEqualTo(String value) {
            addCriterion("lovingheart =", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartNotEqualTo(String value) {
            addCriterion("lovingheart <>", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartGreaterThan(String value) {
            addCriterion("lovingheart >", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartGreaterThanOrEqualTo(String value) {
            addCriterion("lovingheart >=", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartLessThan(String value) {
            addCriterion("lovingheart <", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartLessThanOrEqualTo(String value) {
            addCriterion("lovingheart <=", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartLike(String value) {
            addCriterion("lovingheart like", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartNotLike(String value) {
            addCriterion("lovingheart not like", value, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartIn(List<String> values) {
            addCriterion("lovingheart in", values, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartNotIn(List<String> values) {
            addCriterion("lovingheart not in", values, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartBetween(String value1, String value2) {
            addCriterion("lovingheart between", value1, value2, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andLovingheartNotBetween(String value1, String value2) {
            addCriterion("lovingheart not between", value1, value2, "lovingheart");
            return (Criteria) this;
        }

        public Criteria andContributeIsNull() {
            addCriterion("contribute is null");
            return (Criteria) this;
        }

        public Criteria andContributeIsNotNull() {
            addCriterion("contribute is not null");
            return (Criteria) this;
        }

        public Criteria andContributeEqualTo(String value) {
            addCriterion("contribute =", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeNotEqualTo(String value) {
            addCriterion("contribute <>", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeGreaterThan(String value) {
            addCriterion("contribute >", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeGreaterThanOrEqualTo(String value) {
            addCriterion("contribute >=", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeLessThan(String value) {
            addCriterion("contribute <", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeLessThanOrEqualTo(String value) {
            addCriterion("contribute <=", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeLike(String value) {
            addCriterion("contribute like", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeNotLike(String value) {
            addCriterion("contribute not like", value, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeIn(List<String> values) {
            addCriterion("contribute in", values, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeNotIn(List<String> values) {
            addCriterion("contribute not in", values, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeBetween(String value1, String value2) {
            addCriterion("contribute between", value1, value2, "contribute");
            return (Criteria) this;
        }

        public Criteria andContributeNotBetween(String value1, String value2) {
            addCriterion("contribute not between", value1, value2, "contribute");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctordata
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 24 15:59:00 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctordata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}