package test.model;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.id
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.name
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.website
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.goodcount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private String goodcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.replyCount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private String replycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.patientExpCount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private String patientexpcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.title
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.blog
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    private String blog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.id
     *
     * @return the value of doctor.id
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.id
     *
     * @param id the value for doctor.id
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.name
     *
     * @return the value of doctor.name
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.name
     *
     * @param name the value for doctor.name
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.website
     *
     * @return the value of doctor.website
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.website
     *
     * @param website the value for doctor.website
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.goodcount
     *
     * @return the value of doctor.goodcount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public String getGoodcount() {
        return goodcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.goodcount
     *
     * @param goodcount the value for doctor.goodcount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setGoodcount(String goodcount) {
        this.goodcount = goodcount == null ? null : goodcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.replyCount
     *
     * @return the value of doctor.replyCount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public String getReplycount() {
        return replycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.replyCount
     *
     * @param replycount the value for doctor.replyCount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setReplycount(String replycount) {
        this.replycount = replycount == null ? null : replycount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.patientExpCount
     *
     * @return the value of doctor.patientExpCount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public String getPatientexpcount() {
        return patientexpcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.patientExpCount
     *
     * @param patientexpcount the value for doctor.patientExpCount
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setPatientexpcount(String patientexpcount) {
        this.patientexpcount = patientexpcount == null ? null : patientexpcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.title
     *
     * @return the value of doctor.title
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.title
     *
     * @param title the value for doctor.title
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.blog
     *
     * @return the value of doctor.blog
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.blog
     *
     * @param blog the value for doctor.blog
     *
     * @mbggenerated Thu Dec 18 15:38:40 CST 2014
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }
}