package test.model;

import java.util.Date;

public class Doctordata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String actioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.totalview
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String totalview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.thanks
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String thanks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.warminggifts
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String warminggifts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.votecount
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String votecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.totalarticle
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String totalarticle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.lovingheart
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String lovingheart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.contribute
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String contribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctordata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.id
     *
     * @return the value of doctordata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.id
     *
     * @param id the value for doctordata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.uname
     *
     * @return the value of doctordata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.uname
     *
     * @param uname the value for doctordata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.actioncode
     *
     * @return the value of doctordata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getActioncode() {
        return actioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.actioncode
     *
     * @param actioncode the value for doctordata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setActioncode(String actioncode) {
        this.actioncode = actioncode == null ? null : actioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.totalview
     *
     * @return the value of doctordata.totalview
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getTotalview() {
        return totalview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.totalview
     *
     * @param totalview the value for doctordata.totalview
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setTotalview(String totalview) {
        this.totalview = totalview == null ? null : totalview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.thanks
     *
     * @return the value of doctordata.thanks
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getThanks() {
        return thanks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.thanks
     *
     * @param thanks the value for doctordata.thanks
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setThanks(String thanks) {
        this.thanks = thanks == null ? null : thanks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.warminggifts
     *
     * @return the value of doctordata.warminggifts
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getWarminggifts() {
        return warminggifts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.warminggifts
     *
     * @param warminggifts the value for doctordata.warminggifts
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setWarminggifts(String warminggifts) {
        this.warminggifts = warminggifts == null ? null : warminggifts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.votecount
     *
     * @return the value of doctordata.votecount
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getVotecount() {
        return votecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.votecount
     *
     * @param votecount the value for doctordata.votecount
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setVotecount(String votecount) {
        this.votecount = votecount == null ? null : votecount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.totalarticle
     *
     * @return the value of doctordata.totalarticle
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getTotalarticle() {
        return totalarticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.totalarticle
     *
     * @param totalarticle the value for doctordata.totalarticle
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setTotalarticle(String totalarticle) {
        this.totalarticle = totalarticle == null ? null : totalarticle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.lovingheart
     *
     * @return the value of doctordata.lovingheart
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getLovingheart() {
        return lovingheart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.lovingheart
     *
     * @param lovingheart the value for doctordata.lovingheart
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setLovingheart(String lovingheart) {
        this.lovingheart = lovingheart == null ? null : lovingheart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.contribute
     *
     * @return the value of doctordata.contribute
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getContribute() {
        return contribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.contribute
     *
     * @param contribute the value for doctordata.contribute
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setContribute(String contribute) {
        this.contribute = contribute == null ? null : contribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctordata.timestamp
     *
     * @return the value of doctordata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctordata.timestamp
     *
     * @param timestamp the value for doctordata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}