package test.model;

import java.util.Date;

public class Paymentdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String actioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.payments
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String payments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.groupnum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String groupnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.peoplenum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String peoplenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.topicnum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String topicnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentdata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.id
     *
     * @return the value of paymentdata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.id
     *
     * @param id the value for paymentdata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.uname
     *
     * @return the value of paymentdata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.uname
     *
     * @param uname the value for paymentdata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.actioncode
     *
     * @return the value of paymentdata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getActioncode() {
        return actioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.actioncode
     *
     * @param actioncode the value for paymentdata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setActioncode(String actioncode) {
        this.actioncode = actioncode == null ? null : actioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.payments
     *
     * @return the value of paymentdata.payments
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getPayments() {
        return payments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.payments
     *
     * @param payments the value for paymentdata.payments
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setPayments(String payments) {
        this.payments = payments == null ? null : payments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.groupnum
     *
     * @return the value of paymentdata.groupnum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getGroupnum() {
        return groupnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.groupnum
     *
     * @param groupnum the value for paymentdata.groupnum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setGroupnum(String groupnum) {
        this.groupnum = groupnum == null ? null : groupnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.peoplenum
     *
     * @return the value of paymentdata.peoplenum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getPeoplenum() {
        return peoplenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.peoplenum
     *
     * @param peoplenum the value for paymentdata.peoplenum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setPeoplenum(String peoplenum) {
        this.peoplenum = peoplenum == null ? null : peoplenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.topicnum
     *
     * @return the value of paymentdata.topicnum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getTopicnum() {
        return topicnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.topicnum
     *
     * @param topicnum the value for paymentdata.topicnum
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setTopicnum(String topicnum) {
        this.topicnum = topicnum == null ? null : topicnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentdata.timestamp
     *
     * @return the value of paymentdata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentdata.timestamp
     *
     * @param timestamp the value for paymentdata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}