package test.model;

import java.util.Date;

public class Servicedata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicedata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicedata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicedata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String actioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicedata.allpatients
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String allpatients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicedata.allres
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String allres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicedata.allques
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private String allques;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicedata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicedata.id
     *
     * @return the value of servicedata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicedata.id
     *
     * @param id the value for servicedata.id
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicedata.uname
     *
     * @return the value of servicedata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicedata.uname
     *
     * @param uname the value for servicedata.uname
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicedata.actioncode
     *
     * @return the value of servicedata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getActioncode() {
        return actioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicedata.actioncode
     *
     * @param actioncode the value for servicedata.actioncode
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setActioncode(String actioncode) {
        this.actioncode = actioncode == null ? null : actioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicedata.allpatients
     *
     * @return the value of servicedata.allpatients
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getAllpatients() {
        return allpatients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicedata.allpatients
     *
     * @param allpatients the value for servicedata.allpatients
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setAllpatients(String allpatients) {
        this.allpatients = allpatients == null ? null : allpatients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicedata.allres
     *
     * @return the value of servicedata.allres
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getAllres() {
        return allres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicedata.allres
     *
     * @param allres the value for servicedata.allres
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setAllres(String allres) {
        this.allres = allres == null ? null : allres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicedata.allques
     *
     * @return the value of servicedata.allques
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getAllques() {
        return allques;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicedata.allques
     *
     * @param allques the value for servicedata.allques
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setAllques(String allques) {
        this.allques = allques == null ? null : allques.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicedata.timestamp
     *
     * @return the value of servicedata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicedata.timestamp
     *
     * @param timestamp the value for servicedata.timestamp
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}