package test.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServicedataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public ServicedataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andActioncodeIsNull() {
            addCriterion("actioncode is null");
            return (Criteria) this;
        }

        public Criteria andActioncodeIsNotNull() {
            addCriterion("actioncode is not null");
            return (Criteria) this;
        }

        public Criteria andActioncodeEqualTo(String value) {
            addCriterion("actioncode =", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotEqualTo(String value) {
            addCriterion("actioncode <>", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeGreaterThan(String value) {
            addCriterion("actioncode >", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeGreaterThanOrEqualTo(String value) {
            addCriterion("actioncode >=", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeLessThan(String value) {
            addCriterion("actioncode <", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeLessThanOrEqualTo(String value) {
            addCriterion("actioncode <=", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeLike(String value) {
            addCriterion("actioncode like", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotLike(String value) {
            addCriterion("actioncode not like", value, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeIn(List<String> values) {
            addCriterion("actioncode in", values, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotIn(List<String> values) {
            addCriterion("actioncode not in", values, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeBetween(String value1, String value2) {
            addCriterion("actioncode between", value1, value2, "actioncode");
            return (Criteria) this;
        }

        public Criteria andActioncodeNotBetween(String value1, String value2) {
            addCriterion("actioncode not between", value1, value2, "actioncode");
            return (Criteria) this;
        }

        public Criteria andAllpatientsIsNull() {
            addCriterion("allpatients is null");
            return (Criteria) this;
        }

        public Criteria andAllpatientsIsNotNull() {
            addCriterion("allpatients is not null");
            return (Criteria) this;
        }

        public Criteria andAllpatientsEqualTo(String value) {
            addCriterion("allpatients =", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsNotEqualTo(String value) {
            addCriterion("allpatients <>", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsGreaterThan(String value) {
            addCriterion("allpatients >", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsGreaterThanOrEqualTo(String value) {
            addCriterion("allpatients >=", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsLessThan(String value) {
            addCriterion("allpatients <", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsLessThanOrEqualTo(String value) {
            addCriterion("allpatients <=", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsLike(String value) {
            addCriterion("allpatients like", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsNotLike(String value) {
            addCriterion("allpatients not like", value, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsIn(List<String> values) {
            addCriterion("allpatients in", values, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsNotIn(List<String> values) {
            addCriterion("allpatients not in", values, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsBetween(String value1, String value2) {
            addCriterion("allpatients between", value1, value2, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllpatientsNotBetween(String value1, String value2) {
            addCriterion("allpatients not between", value1, value2, "allpatients");
            return (Criteria) this;
        }

        public Criteria andAllresIsNull() {
            addCriterion("allres is null");
            return (Criteria) this;
        }

        public Criteria andAllresIsNotNull() {
            addCriterion("allres is not null");
            return (Criteria) this;
        }

        public Criteria andAllresEqualTo(String value) {
            addCriterion("allres =", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresNotEqualTo(String value) {
            addCriterion("allres <>", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresGreaterThan(String value) {
            addCriterion("allres >", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresGreaterThanOrEqualTo(String value) {
            addCriterion("allres >=", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresLessThan(String value) {
            addCriterion("allres <", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresLessThanOrEqualTo(String value) {
            addCriterion("allres <=", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresLike(String value) {
            addCriterion("allres like", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresNotLike(String value) {
            addCriterion("allres not like", value, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresIn(List<String> values) {
            addCriterion("allres in", values, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresNotIn(List<String> values) {
            addCriterion("allres not in", values, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresBetween(String value1, String value2) {
            addCriterion("allres between", value1, value2, "allres");
            return (Criteria) this;
        }

        public Criteria andAllresNotBetween(String value1, String value2) {
            addCriterion("allres not between", value1, value2, "allres");
            return (Criteria) this;
        }

        public Criteria andAllquesIsNull() {
            addCriterion("allques is null");
            return (Criteria) this;
        }

        public Criteria andAllquesIsNotNull() {
            addCriterion("allques is not null");
            return (Criteria) this;
        }

        public Criteria andAllquesEqualTo(String value) {
            addCriterion("allques =", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesNotEqualTo(String value) {
            addCriterion("allques <>", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesGreaterThan(String value) {
            addCriterion("allques >", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesGreaterThanOrEqualTo(String value) {
            addCriterion("allques >=", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesLessThan(String value) {
            addCriterion("allques <", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesLessThanOrEqualTo(String value) {
            addCriterion("allques <=", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesLike(String value) {
            addCriterion("allques like", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesNotLike(String value) {
            addCriterion("allques not like", value, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesIn(List<String> values) {
            addCriterion("allques in", values, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesNotIn(List<String> values) {
            addCriterion("allques not in", values, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesBetween(String value1, String value2) {
            addCriterion("allques between", value1, value2, "allques");
            return (Criteria) this;
        }

        public Criteria andAllquesNotBetween(String value1, String value2) {
            addCriterion("allques not between", value1, value2, "allques");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicedata
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 24 15:59:00 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicedata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}