package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Doctorinfo;
import test.model.DoctorinfoExample;

public interface DoctorinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int countByExample(DoctorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int deleteByExample(DoctorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int insert(Doctorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int insertSelective(Doctorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    List<Doctorinfo> selectByExample(DoctorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    Doctorinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int updateByExampleSelective(@Param("record") Doctorinfo record, @Param("example") DoctorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int updateByExample(@Param("record") Doctorinfo record, @Param("example") DoctorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int updateByPrimaryKeySelective(Doctorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctorinfo
     *
     * @mbggenerated Wed Dec 24 14:09:39 CST 2014
     */
    int updateByPrimaryKey(Doctorinfo record);
}