package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Hospitalinfo;
import test.model.HospitalinfoExample;

public interface HospitalinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int countByExample(HospitalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int deleteByExample(HospitalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int insert(Hospitalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int insertSelective(Hospitalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    List<Hospitalinfo> selectByExample(HospitalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    Hospitalinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int updateByExampleSelective(@Param("record") Hospitalinfo record, @Param("example") HospitalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int updateByExample(@Param("record") Hospitalinfo record, @Param("example") HospitalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int updateByPrimaryKeySelective(Hospitalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalinfo
     *
     * @mbggenerated Wed Dec 24 14:15:35 CST 2014
     */
    int updateByPrimaryKey(Hospitalinfo record);
}