package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Paymentdata;
import test.model.PaymentdataExample;

public interface PaymentdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int countByExample(PaymentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int deleteByExample(PaymentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int insert(Paymentdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int insertSelective(Paymentdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    List<Paymentdata> selectByExample(PaymentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    Paymentdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int updateByExampleSelective(@Param("record") Paymentdata record, @Param("example") PaymentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int updateByExample(@Param("record") Paymentdata record, @Param("example") PaymentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int updateByPrimaryKeySelective(Paymentdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdata
     *
     * @mbggenerated Wed Dec 24 15:59:00 CST 2014
     */
    int updateByPrimaryKey(Paymentdata record);
}